/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.siekeusekolah.form;

import javax.swing.JFrame;

/**
 *
 * @author rico
 */
public class FormUtama extends javax.swing.JFrame {

    FormAkun formAkun = new FormAkun();
    FormJurusan formJurusan = new FormJurusan();
    FormAngkatan formAngkatan = new FormAngkatan();
    FormSiswa formSiswa = new FormSiswa();
    FormKelas formKelas = new FormKelas();
    /**
     * Creates new form FormUtama
     */
    public FormUtama() {
        initComponents();
        
        //Fullscreen
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        //Menambah
        desktopPane.add(formAkun);
        desktopPane.add(formJurusan);
        desktopPane.add(formAngkatan);
        desktopPane.add(formSiswa);
        desktopPane.add(formKelas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        masterMenu = new javax.swing.JMenu();
        AkunMenuItem = new javax.swing.JMenuItem();
        AngkatanMenuItem = new javax.swing.JMenuItem();
        JurusanMenuItem = new javax.swing.JMenuItem();
        KelasMenuItem = new javax.swing.JMenuItem();
        SiswaMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        masterMenu.setMnemonic('e');
        masterMenu.setText("Master");

        AkunMenuItem.setMnemonic('t');
        AkunMenuItem.setText("Akun");
        AkunMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AkunMenuItemActionPerformed(evt);
            }
        });
        masterMenu.add(AkunMenuItem);

        AngkatanMenuItem.setMnemonic('y');
        AngkatanMenuItem.setText("Angkatan");
        AngkatanMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AngkatanMenuItemActionPerformed(evt);
            }
        });
        masterMenu.add(AngkatanMenuItem);

        JurusanMenuItem.setMnemonic('d');
        JurusanMenuItem.setText("Jurusan");
        JurusanMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JurusanMenuItemActionPerformed(evt);
            }
        });
        masterMenu.add(JurusanMenuItem);

        KelasMenuItem.setMnemonic('p');
        KelasMenuItem.setText("Kelas");
        KelasMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KelasMenuItemActionPerformed(evt);
            }
        });
        masterMenu.add(KelasMenuItem);

        SiswaMenuItem.setMnemonic('p');
        SiswaMenuItem.setText("Siswa");
        SiswaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiswaMenuItemActionPerformed(evt);
            }
        });
        masterMenu.add(SiswaMenuItem);

        menuBar.add(masterMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void AkunMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AkunMenuItemActionPerformed
        // TODO add your handling code here:
        formAkun.setVisible(true);
    }//GEN-LAST:event_AkunMenuItemActionPerformed

    private void JurusanMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JurusanMenuItemActionPerformed
        // TODO add your handling code here:
        formJurusan.setVisible(true);
    }//GEN-LAST:event_JurusanMenuItemActionPerformed

    private void AngkatanMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AngkatanMenuItemActionPerformed
        // TODO add your handling code here:
        formAngkatan.setVisible(true);
    }//GEN-LAST:event_AngkatanMenuItemActionPerformed

    private void SiswaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiswaMenuItemActionPerformed
        // TODO add your handling code here:
        formSiswa.setVisible(true);
    }//GEN-LAST:event_SiswaMenuItemActionPerformed

    private void KelasMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KelasMenuItemActionPerformed
        // TODO add your handling code here:
        formKelas.setVisible(true);
    }//GEN-LAST:event_KelasMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AkunMenuItem;
    private javax.swing.JMenuItem AngkatanMenuItem;
    private javax.swing.JMenuItem JurusanMenuItem;
    private javax.swing.JMenuItem KelasMenuItem;
    private javax.swing.JMenuItem SiswaMenuItem;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu masterMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
